image: sonicskater/android-gitlab:latest

variables:
  ANDROID_COMPILE_SDK: "26"
  ANDROID_BUILD_TOOLS: "26.0.2"
  ANDROID_SDK_TOOLS: "24.4.1"

before_script:
  - chmod +x ./gradlew
  - export GRADLE_USER_HOME=cache/.gradle
  
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - ./gradlew assembleRelease
  artifacts:
    paths:
    - app/build/outputs/

deploy:
  stage: deploy
  dependencies:
    - build
  environment:
    name: Google Play Alpha Chaannel
    url: https://play.google.com/store?hl=en
  script:
    - ./gradlew app:publishApkRelease